package com.example.aadk_3app1

import android.content.Context
import android.content.SharedPreferences
import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import com.example.aadk_3app1.databinding.ActivityWelcomeBinding

class WelcomeActivity : AppCompatActivity() {

    // 1. ViewBinding
    // First need to enable feature in Gradle
    // AutoGenerated Binding Class that holds the reference to your xml
    // xml - <tag1>_<tag2>_<tag3>.xml
    // auto generated class - Tag1Tag2Tag3Binding
    // Inflate class to connect to our Kotlin file
    // TODO 1: Benefits of Jetpack ViewBinding over normal view binding

    private lateinit var binding: ActivityWelcomeBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityWelcomeBinding.inflate(layoutInflater)
        setContentView(binding.root)

//        val tvWelcome: TextView = findViewById(R.id.tvWelcome)

        // Fetch the name from MainActivity and  display it here
//        val username = intent.getStringExtra(USERNAME_KEY)
//        val password = intent.getStringExtra(PASSWORD_KEY)

        val username = intent.extras?.getString(USERNAME_KEY)
        val password = intent.extras?.getString(PASSWORD_KEY)

//        tvWelcome.text = "Welcome $username \n$password"
        binding.tvWelcome.text = "Welcome $username \n$password"

        // 2. SharedPrefs
        /*
        * Is basically storing all your data in a file, that is only accessible to one app
        * Latest alternative to SharedPrefs is DataStore
        * */

        // How to put our data in shared prefs
        val contactNum = "9876543210"
        val isAdmin = true
        val ageOfUser = 20

        val sharedPrefs = getSharedPreferences(SHARED_PREF_FILE_NAME, Context.MODE_PRIVATE)
        val editor = sharedPrefs.edit()

        editor.putString(SP_CONTACT_NUMBER_KEY, contactNum)
        editor.putBoolean(SP_IS_ADMIN_KEY, isAdmin)
        editor.putInt(SP_AGE_KEY, ageOfUser)

        editor.apply()  // pushes the values in an async manner
//        editor.commit()  // pushes the values asap (in a sync manner)

        // How to access the data from sharedPrefs
        // Assume that you are on an entirely different activity
        val sharedPreferences = getSharedPreferences(SHARED_PREF_FILE_NAME, Context.MODE_PRIVATE)

        val cNum = sharedPreferences.getString(SP_CONTACT_NUMBER_KEY, "No Number Found")
        val isAdm = sharedPreferences.getBoolean(SP_IS_ADMIN_KEY, false)
        val age = sharedPreferences.getInt(SP_AGE_KEY, 0)
        val name = sharedPreferences.getString("nameKey", "No name found")

        Log.d("SharedPreferenceTestTag", "$cNum, $isAdm, $age, $name")
    }
}
